export const SITE_TEXT_DEFAULTS = {
  heroNote: "Bring what you can. Take what helps.",
  whatWeDoKicker: "What we do",
  whatWeDoHeading: "Care is practical.",
  whatWeDoBody: "We mobilize people, supplies, and campus partnerships so a student’s next step can feel a little more possible.",
  impactKicker: "Our impact",
  impactHeading: "Every item carries a little more room to breathe.",
  impactBody: "When a student has food on the table or clothes that feel ready for the day, a community grows stronger.",
  impactBadge: "A growing community, one drive at a time",
  eventsKicker: "Mark your calendar",
  eventsHeading: "Meet us where care is needed.",
  eventsBody: "Plan around the next chance to pack, sort, share, and make a useful difference close to campus.",
  storiesKicker: "The way we show up",
  storiesHeading: "Care moves through people.",
  storiesBody: "Food and clothing access is never a one-person fix. Here is the shared work that keeps care moving across our campuses.",
  storyOneTitle: "A full shelf can steady a week.",
  storyOneBody: "Food drives turn everyday supplies into breathing room—one grocery bag, one meal, one less worry at a time.",
  storyOneContext: "Food access, made tangible.",
  storyTwoTitle: "A good outfit can change how the day begins.",
  storyTwoBody: "Closet days keep quality clothing in circulation for class, work, interviews, and all the in-between moments.",
  storyTwoContext: "Clothing access, shared freely.",
  storyThreeTitle: "Showing up is a skill we share.",
  storyThreeBody: "Packed bags, sorted racks, and welcoming tables begin when students decide to make room for one another.",
  storyThreeContext: "Mutual aid, in motion.",
  actionKicker: "Make room for someone else",
  actionHeading: "What can you carry forward?",
  actionBody: "Show up for a shift, organize a drive, pass along essentials, or help us keep this campus trail moving.",
  volunteerLabel: "Volunteer with us",
  volunteerSubtext: "Sort, deliver, organize, and welcome",
  essentialsLabel: "Give essentials",
  essentialsSubtext: "Fuel food and clothing access",
  footerDescription: "Three campuses, one connected care network, and a shared belief that essentials should never stand in the way of a student’s next step.",
  socialHelper: "Follow the work. Share a drive. Keep the trail moving.",
  footerTagline: "Built for shared strength.",
  aboutHeading: "We make room for each other.",
  aboutIntro: "Can Do ATL is a student-led, multi-campus organization building practical paths to food and clothing access across Georgia Tech, Georgia State, and Kennesaw State.",
  teamKicker: "The people behind the work",
  teamHeading: "Our team, in their own words.",
  teamIntro: "Click a profile to learn more and find each person’s linked social spaces. Team profiles are managed directly from the private staff workspace.",
  joinKicker: "Want to join the work?",
  joinHeading: "There is room at this table.",
  joinBody: "Bring your organizing skills, practical ideas, or an hour to help. Every contribution strengthens the campus trail.",
} as const;

export const SITE_TEXT_KEYS = Object.keys(SITE_TEXT_DEFAULTS) as Array<keyof typeof SITE_TEXT_DEFAULTS>;
export type SiteTextKey = keyof typeof SITE_TEXT_DEFAULTS;
export type SiteTextValues = Record<SiteTextKey, string>;
